Reorganisation of API reference
alphagov/registers-tech-docs pull request #84
Opened 2018-06-21 16:24 UTC by bahmady

Fairly significant reorganisation of the API reference information. Removes use of `curl` to make not only platform-agnostic but also tool-agnostic, and aligns better with specification. 

Should also be more developer-friendly. Feedback welcomed, as ever.

Having some problems with consistency in nomenclature and curly braces, for example with: 

> Get all records that share a `field-value` for a particular field-name

Also just to note that if this PR is approved in principle then we (I) will have to edit the quick start guide's links to match some new tags; the only reason I haven't done that yet is because I mainly want to use this to gather early feedback on this change for the time being. 

Please also see the notes below.

2018-06-21 16:31 UTC, bahmady commented
Please note that under `GET /entries/`:

* start (Optional): Collection page number. Defaults to ?.
* limit (Optional): Collection page size. Defaults to ?. Maximum is ?. 

The '?' are placeholders; I don't know what the appropriate values should be so if someone could fill me in that would be 👍

2018-06-21 16:40 UTC, bahmady commented
I've tried to remove some of the warnings, since the way we need to do this in the tech docs tool isn't very accessible (see https://github.com/alphagov/tech-docs-template/issues/151 which I opened). 

The pagination warnings I'm hoping are covered by the new format (see for example `GET /records/`) but there are warnings under for example `GET /records/{key}` about having the exact identifier to get a match which this PR removes as things stand. The other one is under `GET /download-register` and warns that it will download _every_ item and entry.

2018-06-22 07:57 UTC, arnau requested changes
I really like the way it's going 👍

2018-06-22 07:57 UTC, arnau commented on source/documentation/using_the_api/api_reference.md
> +```
If you add the mark `http` any markdown processor like github's or any that relies on highlight.js will highlight this block accordingly.

E.g.

```md
```http
GET /regitser/ HTTP/2
Host: local-authority-eng.register.gov.uk
...
```
```

2018-06-22 07:57 UTC, arnau commented on source/documentation/using_the_api/api_reference.md
> +* start (Optional): Collection page number. Defaults to ?.
I presume it defaults to 1. If you do:

```
curl -I -H 'Accept: application/json' 'https://local-authority-eng.register.gov.uk/entries/'
```

You'll see a response such as:

```http
HTTP/1.1 200 OK
Content-Type: application/json
Link: <?start=101&limit=100>; rel="next"
```

So it suggests that to get the next page you need to start at 101.

2018-06-22 07:57 UTC, arnau commented on source/documentation/using_the_api/api_reference.md
> +* limit (Optional): Collection page size. Defaults to ?. Maximum is ?.
Based on the above, this defaults to 100. @michaelabenyohai, @gidsg what's the maximum for entries?

2018-06-22 07:57 UTC, arnau commented on source/documentation/using_the_api/api_reference.md
> +Link: <?start=1&limit=10>
I'm being picky here but `Link` is:

```
Link: <?start=101&limit=100>; rel="next"
```

2018-06-22 07:57 UTC, arnau commented on source/documentation/using_the_api/api_reference.md
> +Endpoint: `GET /records/{key}/`
To me, `{key}` is a required parameter so it should be listed in a "Parameters" section.

2018-06-22 07:57 UTC, arnau commented on source/documentation/using_the_api/api_reference.md
> +GET /records/{key} HTTP/2
Here `{key}` should be something specific, given the response, I think the value is `KIN`.

2018-06-22 07:57 UTC, arnau commented on source/documentation/using_the_api/api_reference.md
> +Endpoint: `GET /records/{key}/entries/`
As above, `{key}` is a required parameter.

2018-06-22 07:57 UTC, arnau commented on source/documentation/using_the_api/api_reference.md
> +GET /records/{key}/entries/ HTTP/2
`{key}` needs to be something concrete.

2018-06-22 07:57 UTC, arnau commented on source/documentation/using_the_api/api_reference.md
> +Endpoint: `GET /records/{field-name}/{field-value}/`
`{field-name}` and `{field-value}` are required parameters.

2018-06-22 07:57 UTC, arnau commented on source/documentation/using_the_api/api_reference.md
> +GET /records/{field-name}/{field-value}/ HTTP/2
Concrete values

2018-06-22 07:57 UTC, arnau commented on source/documentation/using_the_api/api_reference.md
> +Link: <?page-index=1&page-size=3>
This `Link` header needs probably a `rel=next` and then values should be higher. Also the `GET` part should contain the parameters, at least the `page-size` as it doesn't default to 100.

2018-06-22 08:05 UTC, arnau commented on source/documentation/using_the_api/api_reference.md
> +GET /register/ HTTP/2
After confirming with @michaelabenyohai, all `HTTP/2` need to change to `HTTP/1.1`.

2018-06-25 07:38 UTC, arnau approved these changes
Approved but waiting on the PLACEHOLDER max. @michaelabenyohai do you know the answer?

2018-06-25 09:30 UTC, michaelabenyohai commented on source/documentation/using_the_api/api_reference.md
> +* limit (Optional): Collection page size. Defaults to 100. Maximum is PLACEHOLDER.
PLACEHOLDER is 5000

2018-06-25 09:35 UTC, bahmady commented
Thank you @michaelabenyohai 

If possible I would like to aim for more than just @arnau's approval of this so will leave it up for review for a bit to see if that's achievable

For the record I'm planning a round of user research on the docs (to do myself) which would include this

2018-06-25 09:46 UTC, michaelabenyohai commented
It looks good. My only thought is that we have lost the structured nature to the contents on the left hand side. I had thought we got good feedback to the contents listing "GET /register", "GET /records" etc. The headings do make sense, but are they as easy for someone to navigate quickly?

2018-06-25 09:49 UTC, bahmady commented
Yes I thought that over the weekend. The best thing to do might be to partly revert and keep the existing (as in, currently live) headers with just the endpoints and then do the new research from there?

2018-06-25 10:21 UTC, michaelabenyohai commented
Yeah that might be good. Does that mean we'll lose the descriptions in those headers? Or will you out them elsewhere?

It might be just me that thinks this, but I do think it was easier to skim the contents previously. It was easier to identify what was "API" and what was other helpful stuff.

2018-06-25 10:28 UTC, bahmady commented
The descriptions are currently in the 'Quick start guide' under the 'Choose an endpoint' header so they'll still reside there regardless. 

There's no real reason why I can't duplicate the descriptions again under a the endpoint header.

e.g. 

>`GET /something/`
>"a plaintext description"
>
> `HTTP response`

The other point is with the new multipage/dropdown functionality coming in soon the left-hand nav is likely to change again. How exactly it changes will depend on user research outcomes, I would imagine.

2018-06-27 07:23 UTC, arnau commented
If we have feedback that having `GET /foo` is better, we should keep it this way.

About the descriptions, I think it's important to have them in context of each endpoint. 

How is the left-hand nav be affected by the multipage functionality? In any case, we will probably not move to multipage during Q2, unless I missed something.

2018-06-27 09:14 UTC, bahmady commented
@arnau It depends on what specific parts of the current docs we choose to put into different pages; if we put any in then they will be accessible via a drop-down menu.

2018-06-27 09:16 UTC, bahmady commented
That's as things stand anyway... it's STC.

2018-06-27 15:00 UTC, bahmady commented
If you guys are OK with it as it is, I'll merge.

2018-06-28 07:13 UTC, arnau commented
@bahmady did you decide to get rid of the descriptions?

2018-06-28 07:32 UTC, arnau approved these changes
👌

2018-06-28 07:44 UTC, michaelabenyohai approved these changes

2018-06-28 07:47 UTC, merged