Fix example in endpoint
alphagov/registers-tech-docs pull request #88
Opened 2018-06-29 15:54 UTC by bahmady

Provides actual values

2018-06-29 16:04 UTC, gidsg requested changes

2018-06-29 16:04 UTC, gidsg commented on source/documentation/using_the_api/api_reference.md
> +GET /entries?start=1&limit=10/ HTTP/1.1
trailing slash here is incorrect.

2018-07-02 07:20 UTC, arnau requested changes

2018-07-02 07:20 UTC, arnau commented on source/documentation/using_the_api/api_reference.md
> +Link: <?start=1&limit=10>; rel="next"
The response for `start=1&limit=10` is `Link: <?start=11&limit=10>; rel="next"`.

You can check the actual values for a response with curl with the flag `-I` (capital i):

```
curl -I "https://country.register.gov.uk/entries?start=1&limit=10"
```

2018-07-02 08:28 UTC, arnau commented on source/documentation/using_the_api/api_reference.md
> +GET /entries?start=1&limit=10 HTTP/1.1
I suspect this should be `/entries/?start=1&limit=10` to keep the style consistent?

2018-07-02 17:29 UTC, arnau approved these changes

2018-07-09 10:59 UTC, bahmady commented
If no objections I'll merge this

2018-07-09 14:31 UTC, merged